import { TRAITORS_CLASSIC_RULE_PACK } from "../config/rulePacks";

/**
 * Backward-compatible alias for default points.
 * Rule-pack aware scoring should prefer `RulePack.points`.
 */

export const SCORING_POINTS = {
  DRAFT_WINNER: TRAITORS_CLASSIC_RULE_PACK.points.DRAFT_WINNER,
  PRED_WINNER: TRAITORS_CLASSIC_RULE_PACK.points.PRED_WINNER,
  PRED_FIRST_OUT: TRAITORS_CLASSIC_RULE_PACK.points.PRED_FIRST_OUT,
  TRAITOR_BONUS: TRAITORS_CLASSIC_RULE_PACK.points.TRAITOR_BONUS,
  PROPHECY_REVERSED_PENALTY:
    TRAITORS_CLASSIC_RULE_PACK.points.PROPHECY_REVERSED_PENALTY,
  WEEKLY_CORRECT_BASE: TRAITORS_CLASSIC_RULE_PACK.points.WEEKLY_CORRECT_BASE,
  WEEKLY_INCORRECT_BASE: TRAITORS_CLASSIC_RULE_PACK.points.WEEKLY_INCORRECT_BASE,
  FINALE_WEEKLY_CORRECT: TRAITORS_CLASSIC_RULE_PACK.points.FINALE_WEEKLY_CORRECT,
  FINALE_WEEKLY_INCORRECT: TRAITORS_CLASSIC_RULE_PACK.points.FINALE_WEEKLY_INCORRECT,
  FINALE_FINAL_WINNER: TRAITORS_CLASSIC_RULE_PACK.points.FINALE_FINAL_WINNER,
  FINALE_LAST_FAITHFUL_STANDING:
    TRAITORS_CLASSIC_RULE_PACK.points.FINALE_LAST_FAITHFUL_STANDING,
  FINALE_LAST_TRAITOR_STANDING:
    TRAITORS_CLASSIC_RULE_PACK.points.FINALE_LAST_TRAITOR_STANDING,
  REDEMPTION_ROULETTE_CORRECT:
    TRAITORS_CLASSIC_RULE_PACK.points.REDEMPTION_ROULETTE_CORRECT,
  REDEMPTION_ROULETTE_CORRECT_NEGATIVE:
    TRAITORS_CLASSIC_RULE_PACK.points.REDEMPTION_ROULETTE_CORRECT_NEGATIVE,
  REDEMPTION_ROULETTE_INCORRECT:
    TRAITORS_CLASSIC_RULE_PACK.points.REDEMPTION_ROULETTE_INCORRECT,
  SHIELD_GAMBIT_CORRECT: TRAITORS_CLASSIC_RULE_PACK.points.SHIELD_GAMBIT_CORRECT,
  SHIELD_GAMBIT_CORRECT_NEGATIVE:
    TRAITORS_CLASSIC_RULE_PACK.points.SHIELD_GAMBIT_CORRECT_NEGATIVE,
  TRAITOR_TRIO_PARTIAL: TRAITORS_CLASSIC_RULE_PACK.points.TRAITOR_TRIO_PARTIAL,
  TRAITOR_TRIO_PERFECT: TRAITORS_CLASSIC_RULE_PACK.points.TRAITOR_TRIO_PERFECT,
  TRAITOR_TRIO_PERFECT_PER_MEMBER:
    TRAITORS_CLASSIC_RULE_PACK.points.TRAITOR_TRIO_PERFECT_PER_MEMBER,
} as const;

export const MULTIPLIERS = {
  /** Multiplier applied to weekly predictions when Double or Nothing is active */
  DOUBLE_OR_NOTHING: 2,

  /** Normal multiplier (no Double or Nothing) */
  NORMAL: 1,
} as const;

export const TIMING = {
  /** Debounce delay (ms) before saving game state to PocketBase */
  SAVE_DEBOUNCE_MS: 500,

  /** Duration (ms) of the sync animation pulse */
  SYNC_ANIMATION_MS: 1000,
} as const;

export const LIMITS = {
  /** Maximum number of weekly submission history entries to keep */
  HISTORY_LIMIT: 200,

  /** Maximum number of weekly score snapshots to keep */
  SCORE_HISTORY_LIMIT: 52,

  /** Number of recent score history entries to show by default */
  SCORE_HISTORY_DEFAULT_DISPLAY: 6,

  /** Number of recent history entries to show by default */
  HISTORY_DEFAULT_DISPLAY: 20,

  /** Number of recent weekly snapshots to show in player timeline */
  PLAYER_TIMELINE_DISPLAY: 6,
} as const;
